version: '3.8'

services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    
  pg_proxy: # https://gal.hagever.com/posts/running-vercel-postgres-locally
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - postgres

volumes:
  db: